# the name of the target operating system
set(CMAKE_SYSTEM_NAME Linux)

if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
  message(STATUS "Target is ARM 32-bit (gnueabihf)")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR arm)
  set(CMAKE_C_COMPILER /usr/bin/arm-linux-gnueabihf-gcc)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
  message(STATUS "Target is AArch64")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR aarch64)
  set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ppc" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "powerpc")
  message(STATUS "Target is PowerPC 32-bit")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR powerpc)
  set(CMAKE_C_COMPILER /usr/bin/powerpc-linux-gnu-gcc)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  message(STATUS "Target is x86_64")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR x86_64)
  set(CMAKE_C_COMPILER /usr/bin/gcc)
else()
    message(STATUS "Target processor is unknown or not specifically handled: ${CMAKE_SYSTEM_PROCESSOR}")
endif()
